apiVersion: v1
kind: Service
metadata:
  name: {{ include "finops-http-rest-queue-chart.fullname" . }}-service
  labels:
  {{- include "finops-http-rest-queue-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: http-rest-queue
  {{- include "finops-http-rest-queue-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 }}
